name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 0 * * *' # 6 AM Asian time
    - cron: '0 6 * * *' # 12 PM Asian time
    - cron: '0 12 * * *' # 6 PM Asian time
    - cron: '0 15 * * *' # 9 PM Asian time

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 40

      - uses: christosgalano/delete-workflow-runs@v1.0.0
        with:
          owner: long18
          repo: auto-streak-duolingo
          token: ${{ secrets.GITHUB_TOKEN }}
