name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: echo "::set-output name=delay::$((RANDOM % 50))"
        description: 'Number of lessons to be done'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.lessons }}

      - name: Remove expired workflow runs
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "7 days" # Delete artifacts older than 7 days
