name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be done'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate Random Delay
        id: random-delay
        run: echo "delay=$((RANDOM % 10))" >> $GITHUB_OUTPUT  # Generates a random delay between 0 and 3600 seconds

          # Your action commands go here
      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ steps.random-delay.outputs.delay }}

      - name: Remove expired workflow runs
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "7 days" # Delete artifacts older than 7 days
